import test from 'node:test';
import assert from 'node:assert/strict';
import { buildRedditShareText, buildToxicCompilationShareText, redditBlockquote } from '../src/lib/shareText.js';

test('prefixes every line so multiline text stays quoted on Reddit mobile', () => {
  assert.equal(redditBlockquote('first line\n\nsecond line'), '> first line\n>\n> second line');
});

test('truncates copied receipts to 50 characters', () => {
  assert.equal(redditBlockquote('a'.repeat(55)), `> ${'a'.repeat(50)}...`);
});

test('builds opener, quote-source pairs, closing, and app link in paste order', () => {
  const text = buildRedditShareText({
    sources: [{ body: 'first quote', permalink: 'https://reddit.com/one' }, { body: 'second quote', permalink: 'https://reddit.com/two' }],
    opener: 'You keep contradicting yourself.',
    answer: 'That is the final comment.',
    origin: 'https://reddit-pi.live',
  });
  assert.equal(text, 'You keep contradicting yourself.\n\n> first quote\n[Source](https://reddit.com/one)\n\n> second quote\n[Source](https://reddit.com/two)\n\nThat is the final comment.\n\n^(This reply was generated by reddit-pi.) ^([Website](https://reddit-pi.live))');
});

test('quotes a post title and body as one compact receipt', () => {
  const text = buildRedditShareText({
    sources: [{ type: 'post', title: 'Post title', body: 'Post body', permalink: 'https://reddit.com/post' }],
    opener: 'Opening.',
    answer: 'Closing.',
    origin: 'https://reddit-pi.live',
  });
  assert.match(text, /> Post title\n> Post body\n\[Source\]\(https:\/\/reddit.com\/post\)/);
  assert.match(text, /\^\(This reply was generated by reddit-pi\.\) \^\(\[Website\]\(https:\/\/reddit-pi\.live\)\)$/);
});

test('share text always uses the canonical site instead of an old host', () => {
  const text = buildRedditShareText({
    sources: [],
    opener: 'One line.',
    answer: 'Final comment.',
    origin: 'https://mod-vetting-api.onrender.com',
  });

  assert.match(text, /\[Website\]\(https:\/\/reddit-pi\.live\)/);
  assert.doesNotMatch(text, /onrender\.com/);
});
test('builds a ten-source toxic compilation in mobile Reddit format', () => {
  const sources = Array.from({ length: 10 }, (_, index) => ({
    id: 'c' + index, quote: 'focused quote ' + index, body: 'focused quote ' + index + ' with context',
    permalink: 'https://reddit.com/c' + index,
  }));
  const text = buildToxicCompilationShareText({ username: 'example', sources });
  assert.ok(text.startsWith('Best comments from u/example\n\n> focused quote 0...'));
  assert.equal((text.match(/\[Source\]/g) || []).length, 10);
  assert.ok(text.includes('Sourced by reddit-pi'));
  assert.ok(text.includes('https://reddit-pi.live'));
});