import { sourceText } from './sourceContent.js';

export const CANONICAL_SITE_URL = 'https://reddit-pi.live';

export function redditBlockquote(content, limit = 50) {
  const raw = typeof content === 'string' ? (content || 'Content unavailable.') : sourceText(content);
  const excerpt = `${raw.slice(0, limit).trim()}${raw.length > limit ? '...' : ''}`;
  return excerpt.split(/\r?\n/).map((line) => line ? `> ${line}` : '>').join('\n');
}

export function buildRedditShareText({ sources, opener = '', answer = '' }) {
  const selected = sources.slice(0, 3);
  const receipts = selected.map((source) => `${redditBlockquote(source)}\n[Source](${source.permalink})`).join('\n\n');
  const signature = `^(This reply was generated by reddit-pi.) ^([Website](${CANONICAL_SITE_URL}))`;
  return [opener.trim(), receipts, answer.trim(), signature].filter(Boolean).join('\n\n');
}
