import { sourceText } from './sourceContent.js';

export const CANONICAL_SITE_URL = 'https://reddit-pi.live';

export function redditBlockquote(content, limit = 50) {
  const raw = typeof content === 'string' ? (content || 'Content unavailable.') : sourceText(content);
  const excerpt = `${raw.slice(0, limit).trim()}${raw.length > limit ? '...' : ''}`;
  return excerpt.split(/\r?\n/).map((line) => line ? `> ${line}` : '>').join('\n');
}

export function buildRedditShareText({ sources, opener = '', answer = '' }) {
  const selected = sources.slice(0, 3);
  const receipts = selected.map((source) => `${redditBlockquote(source)}\n[Source](${source.permalink})`).join('\n\n');
  const signature = `^(This reply was generated by reddit-pi.) ^([Website](${CANONICAL_SITE_URL}))`;
  return [opener.trim(), receipts, answer.trim(), signature].filter(Boolean).join('\n\n');
}

export function buildToxicCompilationShareText({ username, sources = [] }) {
  const receipts = sources.slice(0, 10).map((source) => {
    const focused = source.quote || sourceText(source);
    const excerpt = focused.slice(0, 50).trim();
    const omitted = focused.length > 50 || (source.quote && source.quote !== source.body);
    return `${redditBlockquote(excerpt + (omitted ? '...' : ''), 53)}\n[Source](${source.permalink})`;
  }).join('\n\n');
  return [`Best comments from u/${username}`, receipts,
    `^(Sourced by reddit-pi.) ^([Website](${CANONICAL_SITE_URL}))`].filter(Boolean).join('\n\n');
}